## **NumPY course**






In [ ]:
# to install numpy 1. conda install numpy in anaconda and 2. pip install numpy in other programming softwares.

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
my_list =[1,2,3,4]

In [ ]:
my_list

[1, 2, 3, 4]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(my_list)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(10) # with only one number it starts from 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2) # the three numbers state the start, stop and the step size.

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.arange(0,24,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [ ]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((1,1))

array([[0.]])

In [ ]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((9,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,9,17)

array([0.    , 0.5625, 1.125 , 1.6875, 2.25  , 2.8125, 3.375 , 3.9375,
       4.5   , 5.0625, 5.625 , 6.1875, 6.75  , 7.3125, 7.875 , 8.4375,
       9.    ])

In [ ]:
#creating and identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# randon methods

In [ ]:
np.random.rand(5)

array([0.37541131, 0.77596557, 0.99864622, 0.02330945, 0.17117692])

In [ ]:
# which gives a one dimensional array with 5 random uniform positive distributions.

In [ ]:
np.random.rand(6,6)

array([[0.04064136, 0.15892825, 0.85091529, 0.86436502, 0.41718972,
        0.98802365],
       [0.25032029, 0.2888423 , 0.43976988, 0.2104503 , 0.50915276,
        0.77201221],
       [0.27631301, 0.15361864, 0.0361661 , 0.51085004, 0.64289024,
        0.23485022],
       [0.71419235, 0.87653494, 0.5453269 , 0.89780867, 0.7504901 ,
        0.48234761],
       [0.3055314 , 0.45281533, 0.59884536, 0.22293462, 0.83198962,
        0.9742712 ],
       [0.35444696, 0.86817547, 0.18145714, 0.38785052, 0.69449875,
        0.37167624]])

In [ ]:
# no need of putting tuples put the row and column value  separted with ',' it willgive a matrix.

In [ ]:
#for a normalor gaussian distribution use .randn in place of .rand

In [ ]:
np.random.randn(2)

array([ 1.3927123, -0.5464971])

In [ ]:
np.random.randn(3,5) # for two dimensional matrix

array([[-0.36669328,  1.72774395, -0.62706762, -1.70838655, -1.12728359],
       [ 1.42615521, -1.07257933,  0.65710044, -0.90567934,  0.26166733],
       [-1.21175673, -1.00619353, -0.32400543,  0.35410996, -0.22563998]])

In [ ]:
np.random.randint(0,100) # selects a random integer between 0 to 100 where 0 is inclusive and 100 is not.

58

In [ ]:
np.random.randint(-10,20,10) #the third number denotes the number of elements in the array.

array([16,  7, 12, -9, -4, 15, 15, 10, 11,  7])

In [ ]:
#reshape method

In [ ]:
arr = np.arange(25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5) #reshapes into a 2d matrix.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(5,10) # reshape value needs to be equal to the total no.of elements.

ValueError: ignored

In [ ]:
import numpy as np

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
ranarr

array([22, 37, 21, 27,  2,  5, 26, 18, 11,  0])

In [ ]:
#max value of the array

In [ ]:
ranarr.max()

37

In [ ]:
#mmin value of the array

In [ ]:
ranarr.min()

0

In [ ]:
# to fing the index location of min value

In [ ]:
ranarr.argmax()

1

In [ ]:
ranarr.argmin() # to find the index location of min value

9

In [ ]:
arr.shape #to check the shape of he array, here it is 1d array.

(25,)

In [ ]:
arr = arr.reshape(5,5) # it is to reshape the previously assigned array to new dimension here as a 2 d matrix.

In [ ]:
arr.shape # here it can be seen that the new assigned shape is 2d matrix of dimensions 5*5

(5, 5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.dtype #to find the datatype of the array.

dtype('int64')

In [ ]:
ranarr.dtype

dtype('int64')

In [ ]:
ranarr.shape

(10,)

In [ ]:
ranarr = ranarr.reshape(2,5)

In [ ]:
ranarr

array([[22, 37, 21, 27,  2],
       [ 5, 26, 18, 11,  0]])

In [ ]:
# to use only randomint we can the below function

In [ ]:
from numpy.random import randint

In [ ]:
randint(0,18,6)

array([17,  6,  0, 11, 13,  0])

#**NumPy Indexing and Selection**

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr #indexing starts at 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[2:6] #using slice notations

array([2, 3, 4, 5])

In [ ]:
arr[:6] # or can be typed arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[5:] # grabbing everything beyond the 5th position

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5] = 100 #assigning values

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_array = arr[0:5]

In [ ]:
slice_of_array

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_array[:] = 99

In [ ]:
arr #the changes done in the sliceofarray is also reflected in arr, as it is changing to stop that from happening we need to create a copy of the array and change it epping the original un disturbed.

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[:] = 200

In [ ]:
arr_copy# the copied array is assigned a value and it is reflected.

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [ ]:
arr # the original array is unchanged as th eoperations are applicable only for the copied array.

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

#**Creating a 2d Array**

In [ ]:
import numpy as np

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# grabbing an element in the matrix for eg. to grab 1 in the above matrix

In [ ]:
arr_2d[0]

array([1, 2, 3])

In [ ]:
#to grab 9 
arr_2d[2][2]

9

In [ ]:
#similarly to grab 5
arr_2d[1][1]

5

In [ ]:
#similarly to grab 1
arr_2d[0][0]

1

In [ ]:
# and to make it more easy we can use',' and separate the columns and rows.

In [ ]:
arr_2d[1,1]

5

In [ ]:
arr_2d[0,2]

3

In [ ]:
#to grab more than pone element in the matrix or a sub matrix we have to use slice notations

In [ ]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
#similarly 
arr_2d[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

#**conditional selection **

In [ ]:
ar = np.arange(0,11)

In [ ]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ar > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
bool_ar = ar > 5

In [ ]:
bool_ar

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
ar[bool_ar]

array([ 6,  7,  8,  9, 10])

In [ ]:
# all this operations can be done combinedly

In [ ]:
ar[ar>5] #this is the standard syntax notation which will be used for coditional selection.

array([ 6,  7,  8,  9, 10])

In [ ]:
ar[ar<3]

array([0, 1, 2])

In [ ]:
ar_2d = np.arange(50).reshape(5,10)

In [ ]:
ar_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
ar_2d[2:4,7:]

array([[27, 28, 29],
       [37, 38, 39]])

In [ ]:
ar_2d[0:,0:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41]])

In [ ]:
ar_2d[1:4,4:7]

array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

#**NumPy Operations**


*   **Array with Array**
*   **Array with Scalars**
*   **Universal Array Functions**






In [ ]:
import numpy as np

In [ ]:
ray = np.arange(0,11)

In [ ]:
ray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ray + ray #addition of arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
ray - ray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ray2 = ray.copy()

In [ ]:
ray + ray2

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210])

In [ ]:
ray2[:] = 200

In [ ]:
ray + ray2

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210])

In [ ]:
ray * ray # array multiplication can also be done

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
ray * ray2

array([   0,  200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [ ]:
ray/ray2

array([0.   , 0.005, 0.01 , 0.015, 0.02 , 0.025, 0.03 , 0.035, 0.04 ,
       0.045, 0.05 ])

In [ ]:
# Scalar Operations.

In [ ]:
ray + 100 #addition of scalar to arrays

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
ray * 100 #multiplication of scalar to arrays

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
ray - 100 #subtraction of scalar to arrays

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [ ]:
ray / 10 #division of scalar to arrays

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
ray % 5 # mod function with scalar division giving the remainder

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0])

In [ ]:
ray / ray #when you divide 0/0 you will get nan value, it is undefined but still it will be shown after showing a error message.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
 1/ray # anything divide by zero shows a warning and gives the value inf that is infinity

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
ray ** 4 #this gives the powered value

array([    0,     1,    16,    81,   256,   625,  1296,  2401,  4096,
        6561, 10000])

In [ ]:
#universal array functons

In [ ]:
# to get the squareroot value of the array
np.sqrt(ray) 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
# to get the exponential value of the array
np.exp(ray) 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
# thats the same thing as the method ray.max()
np.max(ray)

10

In [ ]:
ray.max() # the above function also gives the same value

10

In [ ]:
#trigonometric functions 
np.sin(ray)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.cos(ray)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [ ]:
np.tan(ray)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [ ]:
np.log(ray) #Logarithmic functions, the log(0) will give -infinity that is -inf. which also shows an error of runtime warning.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
#lets check wether it will work work 2d arrays (matices)

In [ ]:
matray = np.arange(20).reshape(4,5)

In [ ]:
matray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
matray + matray

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [ ]:
matray * matray

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [ ]:
matray / matray

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [ ]:
matray - matray

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
matray ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [ ]:
np.sin(matray)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [ ]:
np.exp(matray)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08]])

In [ ]:
np.log(matray)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898]])

In [ ]:
4 * matray

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76]])

In [ ]:
matray / 10

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

In [ ]:
10 / matray

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[        inf, 10.        ,  5.        ,  3.33333333,  2.5       ],
       [ 2.        ,  1.66666667,  1.42857143,  1.25      ,  1.11111111],
       [ 1.        ,  0.90909091,  0.83333333,  0.76923077,  0.71428571],
       [ 0.66666667,  0.625     ,  0.58823529,  0.55555556,  0.52631579]])

In [ ]:
matray % 2

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [ ]:
np.max(matray)

19

In [ ]:
np.min(matray)

0

In [ ]:
matray2 = np.arange(20).reshape(4,5)

In [ ]:
matray2[0:2, 3:] = 200

In [ ]:
matray2

array([[  0,   1,   2, 200, 200],
       [  5,   6,   7, 200, 200],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [ ]:
matray[:2] + matray2[:2] #from this we can see that the matrix can be divided in to sub matrices and can be added.

array([[  0,   2,   4, 203, 204],
       [ 10,  12,  14, 208, 209]])

In [ ]:
matray[0:2,0:2] * matray2[0:2,3:]

array([[   0,  200],
       [1000, 1200]])